# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['PSQL_PORT'] %>

development:
  <<: *default
  database: epresto_development
  host: <%= ENV['PSQL_HOST'] %>
  username: <%= ENV['PSQL_USER'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>

test:
  <<: *default
  database: epresto_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: epresto_production
  username: <%= ENV['PSQL_USER_PRODUCTION'] %>
