# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.PSQL_USER %>
  password: <%= Rails.application.credentials.PSQL_PASSWORD %>

development:
  <<: *default
  database: epresto_development

test:
  <<: *default
  database: epresto_test
#
production:
  <<: *default
  database: epresto_production
