class RemoveManyColumnsFromItem < ActiveRecord::Migration[7.0]
  def change
    remove_column :items, :external_id_exemption_reason
    remove_column :items, :product_category
    remove_column :items, :product_subcategory
    remove_column :items, :recommended_browse_nodes1
    remove_column :items, :recommended_browse_nodes2
    remove_column :items, :recommended_browse_nodes3
    remove_column :items, :recommended_browse_nodes4
    remove_column :items, :recommended_browse_nodes5
    remove_column :items, :package_level
    remove_column :items, :package_contains_quantity
    remove_column :items, :package_contains_identifier
    remove_column :items, :is_package_level_orderable
    remove_column :items, :item_type_name
    remove_column :items, :manufacturer
    remove_column :items, :list_price
    remove_column :items, :list_price_currency
    remove_column :items, :cost_price
    remove_column :items, :cost_price_currency
    remove_column :items, :bullet_point1
    remove_column :items, :bullet_point2
    remove_column :items, :bullet_point3
    remove_column :items, :bullet_point4
    remove_column :items, :bullet_point5
    remove_column :items, :generic_keyword1
    remove_column :items, :generic_keyword2
    remove_column :items, :generic_keyword3
    remove_column :items, :generic_keyword4
    remove_column :items, :generic_keyword5
    remove_column :items, :number_of_items
    remove_column :items, :product_description
    remove_column :items, :color
    remove_column :items, :occasion1
    remove_column :items, :occasion2
    remove_column :items, :occasion3
    remove_column :items, :occasion4
    remove_column :items, :occasion5
    remove_column :items, :serving_recommendation
    remove_column :items, :is_the_item_heat_Sensitive?
    remove_column :items, :melting_temperature_degrees_celsius
    remove_column :items, :melting_temperature_unit
    remove_column :items, :temperature_rating
    remove_column :items, :material_type_free1
    remove_column :items, :material_type_free2
    remove_column :items, :material_type_free3
    remove_column :items, :material_type_free4
    remove_column :items, :material_type_free5
    remove_column :items, :flavor
    remove_column :items, :form_factor
    remove_column :items, :ingredients
    remove_column :items, :cuisine
    remove_column :items, :each_unit_count
    remove_column :items, :allergen_information1
    remove_column :items, :allergen_information2
    remove_column :items, :allergen_information3
    remove_column :items, :allergen_information4
    remove_column :items, :allergen_information5
    remove_column :items, :is_product_expirable
    remove_column :items, :product_expiration_type
    remove_column :items, :fulfillment_center_shelf_life
    remove_column :items, :fulfillment_center_shelf_life_Unit
    remove_column :items, :item_form
    remove_column :items, :specialty1
    remove_column :items, :specialty2
    remove_column :items, :specialty3
    remove_column :items, :specialty4
    remove_column :items, :specialty5
    remove_column :items, :release_date
    remove_column :items, :product_site_launch_date
    remove_column :items, :unit_count
    remove_column :items, :unit_count_type
    remove_column :items, :container_type
    remove_column :items, :manufacturer_contact_information1
    remove_column :items, :manufacturer_contact_information2
    remove_column :items, :manufacturer_contact_information3
    remove_column :items, :manufacturer_contact_information4
    remove_column :items, :manufacturer_contact_information5
    remove_column :items, :diet_type1
    remove_column :items, :diet_type2
    remove_column :items, :diet_type3
    remove_column :items, :nut_or_seed_type1
    remove_column :items, :nut_or_seed_type2
    remove_column :items, :nut_or_seed_type3
    remove_column :items, :nut_or_seed_type4
    remove_column :items, :nut_or_seed_type5
    remove_column :items, :directions
    remove_column :items, :region_of_origin
    remove_column :items, :country_of_origin
    remove_column :items, :warranty_description1
    remove_column :items, :warranty_description2
    remove_column :items, :warranty_description3
    remove_column :items, :warranty_description4
    remove_column :items, :warranty_description5
    remove_column :items, :safety_warning
    remove_column :items, :are_batteries_required?
    remove_column :items, :are_batteries_included?
    remove_column :items, :battery_cell_composition
    remove_column :items, :battery_weight
    remove_column :items, :battery_weight_unit
    remove_column :items, :number_of_batteries1
    remove_column :items, :battery_type1
    remove_column :items, :number_of_batteries2
    remove_column :items, :battery_type2
    remove_column :items, :number_of_batteries3
    remove_column :items, :battery_type3
    remove_column :items, :number_of_batteries4
    remove_column :items, :battery_type4
    remove_column :items, :number_of_batteries5
    remove_column :items, :battery_type5
    remove_column :items, :number_of_lithium_metal_cells
    remove_column :items, :number_of_lithium_ion_cells
    remove_column :items, :lithium_battery_energy_content
    remove_column :items, :lithium_battery_energy_content_unit
    remove_column :items, :lithium_battery_packaging
    remove_column :items, :lithium_battery_weight
    remove_column :items, :lithium_battery_weight_unit
    remove_column :items, :dangerous_goods_regulations1
    remove_column :items, :dangerous_goods_regulations2
    remove_column :items, :dangerous_goods_regulations3
    remove_column :items, :dangerous_goods_regulations4
    remove_column :items, :dangerous_goods_regulations5
    remove_column :items, :contains_liquid_contents?
    remove_column :items, :hazmat_aspect
    remove_column :items, :hazmat
    remove_column :items, :liquid_contents_uescription
    remove_column :items, :safety_data_sheet_sds_or_msds_url
    remove_column :items, :item_weight
    remove_column :items, :item_weight_unit
    remove_column :items, :product_compliance_certificate
    remove_column :items, :regulatory_organization_name
    remove_column :items, :compliance_certification_status
    remove_column :items, :compliance_certification_value
    remove_column :items, :certification_metadata
    remove_column :items, :certification_date_of_issue
    remove_column :items, :certification_expiration_date
    remove_column :items, :gHS_class
    remove_column :items, :liquid_packaging_type
    remove_column :items, :is_the_liquid_product_double_sealed?
    remove_column :items, :mandatory_cautionary_statement1
    remove_column :items, :mandatory_cautionary_statement2
    remove_column :items, :mandatory_cautionary_statement3
    remove_column :items, :mandatory_cautionary_statement4
    remove_column :items, :mandatory_cautionary_statement5
    remove_column :items, :liquid_volume_unit
    remove_column :items, :liquid_volume
    remove_column :items, :compliance_regulation_type1
    remove_column :items, :regulatory_identification1
    remove_column :items, :compliance_regulation_type2
    remove_column :items, :regulatory_identification2
    remove_column :items, :compliance_regulation_type3
    remove_column :items, :regulatory_identification3
    remove_column :items, :compliance_regulation_type4
    remove_column :items, :regulatory_identification4
    remove_column :items, :compliance_regulation_type5
    remove_column :items, :regulatory_identification5
    remove_column :items, :item_length
    remove_column :items, :item_length_unit
    remove_column :items, :item_width
    remove_column :items, :item_width_unit
    remove_column :items, :item_height
    remove_column :items, :item_height_unit
    remove_column :items, :item_package_length
    remove_column :items, :package_length_unit
    remove_column :items, :item_package_width
    remove_column :items, :package_width_unit
    remove_column :items, :item_package_height
    remove_column :items, :package_height_unit
    remove_column :items, :package_weight
    remove_column :items, :package_weight_unit
    remove_column :items, :item_volume
    remove_column :items, :item_volume_unit
    remove_column :items, :items_per_inner_pack
    remove_column :items, :inner_packs_per_master_pack
    remove_column :items, :master_pack_layers_per_pallet_quantity
    remove_column :items, :master_packs_per_layer_quantity
  end
end
