name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST: ${{ secrets.PSQL_HOST }}
          POSTGRES_USER: ${{ secrets.PSQL_USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_PASSWORD_TEST }}
          POSTGRES_DB: epresto_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-v1-${{ hashFiles('Gemfile.lock') }}

      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-v1-${{ hashFiles('yarn.lock') }}

      - name: Assets precompile
        run: RAILS_ENV=test bundle exec rails assets:precompile

      - name: Test with RSpec
        env:
          PSQL_HOST: localhost
          PSQL_USER: ${{ secrets.PSQL_USER_TEST }}
          PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD_TEST }}
          RAILS_ENV: test
        run: |
          bundle exec rails db:setup
          bundle exec rails db:migrate
          bundle exec rspec

  deploy:
    name: Deploy app to AWS
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-v1-${{ hashFiles('Gemfile.lock') }}

      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - name: Deploy
        env:
          DEPLOY_SSH_KEY_PATH: ~/.ssh/app_key
          PRODUCTION_HOST: ${{secrets.TARGET_HOSTNAME}}
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/app_key
          chmod 600 ~/.ssh/app_key
          eval `ssh-agent` && ssh-add ~/.ssh/app_key && ssh-add -l
          bundle exec cap production deploy
